use super::*;
use crate::repos::{TrackRepository, TrackRow};

fn track(
    server: &str,
    id: &str,
    title: &str,
    artist: &str,
    album: &str,
    album_id: &str,
    artist_id: &str,
) -> TrackRow {
    TrackRow {
        server_id: server.into(),
        id: id.into(),
        title: title.into(),
        title_sort: None,
        artist: Some(artist.into()),
        artist_id: Some(artist_id.into()),
        album: album.into(),
        album_id: Some(album_id.into()),
        album_artist: Some(artist.into()),
        duration_sec: 200,
        track_number: Some(1),
        disc_number: Some(1),
        year: None,
        genre: None,
        suffix: None,
        bit_rate: None,
        size_bytes: None,
        cover_art_id: Some(format!("cv_{album_id}")),
        starred_at: None,
        user_rating: None,
        play_count: None,
        played_at: None,
        server_path: None,
        library_id: None,
        isrc: None,
        mbid_recording: None,
        bpm: None,
        replay_gain_track_db: None,
        replay_gain_album_db: None,
        replay_gain_peak: None,
        content_hash: None,
        server_updated_at: None,
        server_created_at: None,
        deleted: false,
        synced_at: 1,
        raw_json: "{}".into(),
    }
}
