name: Publish to winget
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@latest
        with:
          identifier: Psychotoxical.Psysonic
          installers-regex: '_x64-setup\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
